services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./integrationAPI
      dockerfile: Dockerfile
    container_name: flask_api_container
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    volumes:
      - ./integrationAPI:/app
    depends_on:
      mysql:
        condition: service_healthy

networks:
  mynetwork:
    driver: bridge
