from datetime import date

concepts = [
  {
    "id": "1",
    "subject_nb": "Informatikk",
    "subject_nn": "Informatikk",
    "subject_en": "Computer Science",
    "preferredLabel_nb": "Algoritme",
    "preferredLabel_nn": "Algoritme",
    "preferredLabel_en": "Algorithm",
    "alternativeLabel_nb": "Prosedyre",
    "alternativeLabel_nn": "Prosedyre",
    "alternativeLabel_en": "Procedure",
    "definition_nb": "En presis beskrivelse av en serie operasjoner som skal utføres for å løse et problem.",
    "definition_nn": "Ei presis skildring av ein serie operasjonar som skal utførast for å løyse eit problem.",
    "definition_en": "A precise description of a series of operations to be performed to solve a problem.",
    "definition_lastUpdated": "2024-07-01"
  },
  {
    "id": "2",
    "subject_nb": "Matematikk",
    "subject_nn": "Matematikk",
    "subject_en": "Mathematics",
    "preferredLabel_nb": "Integral",
    "preferredLabel_nn": "Integral",
    "preferredLabel_en": "Integral",
    "alternativeLabel_nb": "Antiderivat",
    "alternativeLabel_nn": "Antiderivert",
    "alternativeLabel_en": "Antiderivative",
    "definition_nb": "En matematisk operasjon som brukes til å beregne areal under en kurve eller volum av en figur.",
    "definition_nn": "Ein matematisk operasjon som vert nytta til å rekne ut areal under ei kurve eller volum av ein figur.",
    "definition_en": "A mathematical operation used to calculate the area under a curve or the volume of a figure.",
    "definition_lastUpdated": "2024-07-02"
  },
  {
    "id": "3",
    "subject_nb": "Fysikk",
    "subject_nn": "Fysikk",
    "subject_en": "Physics",
    "preferredLabel_nb": "Entropi",
    "preferredLabel_nn": "Entropi",
    "preferredLabel_en": "Entropy",
    "alternativeLabel_nb": "Uorden",
    "alternativeLabel_nn": "Uorden",
    "alternativeLabel_en": "Disorder",
    "definition_nb": "Et mål på graden av uorden eller tilfeldighet i et system.",
    "definition_nn": "Eit mål på graden av uorden eller tilfeldigheit i eit system.",
    "definition_en": "A measure of the degree of disorder or randomness in a system.",
    "definition_lastUpdated": "2024-07-03"
  },
  {
    "id": "4",
    "subject_nb": "Biologi",
    "subject_nn": "Biologi",
    "subject_en": "Biology",
    "preferredLabel_nb": "Fotosyntese",
    "preferredLabel_nn": "Fotosyntese",
    "preferredLabel_en": "Photosynthesis",
    "alternativeLabel_nb": "Karbonfiksering",
    "alternativeLabel_nn": "Karbonfiksering",
    "alternativeLabel_en": "Carbon fixation",
    "definition_nb": "Prosessen der planter og andre organismer omdanner lysenergi til kjemisk energi som kan brukes til å drive organismens aktiviteter.",
    "definition_nn": "Prosessen der plantar og andre organismar omdannar lysenergi til kjemisk energi som kan brukast til å drive organismen sine aktivitetar.",
    "definition_en": "The process by which plants and other organisms convert light energy into chemical energy that can be used to fuel the organism's activities.",
    "definition_lastUpdated": "2024-07-04"
  },
  {
    "id": "5",
    "subject_nb": "Kjemi",
    "subject_nn": "Kjemi",
    "subject_en": "Chemistry",
    "preferredLabel_nb": "Katalysator",
    "preferredLabel_nn": "Katalysator",
    "preferredLabel_en": "Catalyst",
    "alternativeLabel_nb": "Reaksjonsakselerator",
    "alternativeLabel_nn": "Reaksjonsakselerator",
    "alternativeLabel_en": "Reaction accelerator",
    "definition_nb": "Et stoff som øker hastigheten på en kjemisk reaksjon uten selv å bli forbrukt i prosessen.",
    "definition_nn": "Eit stoff som aukar farten på ein kjemisk reaksjon utan sjølv å bli forbrukt i prosessen.",
    "definition_en": "A substance that increases the rate of a chemical reaction without itself being consumed in the process.",
    "definition_lastUpdated": "2024-07-05"
  },
  {
    "id": "6",
    "subject_nb": "Geologi",
    "subject_nn": "Geologi",
    "subject_en": "Geology",
    "preferredLabel_nb": "Tektonisk plate",
    "preferredLabel_nn": "Tektonisk plate",
    "preferredLabel_en": "Tectonic plate",
    "alternativeLabel_nb": "Litosfæreplate",
    "alternativeLabel_nn": "Litosfæreplate",
    "alternativeLabel_en": "Lithospheric plate",
    "definition_nb": "Et massivt, irregulært formet stykke av jordens litosfære som beveger seg i forhold til andre plater.",
    "definition_nn": "Eit massivt, irregulært forma stykke av jorda si litosfære som beveger seg i forhold til andre plater.",
    "definition_en": "A massive, irregularly shaped slab of solid rock, generally composed of both continental and oceanic lithosphere, that moves relative to other plates.",
    "definition_lastUpdated": "2024-07-06"
  },
  {
    "id": "7",
    "subject_nb": "Psykologi",
    "subject_nn": "Psykologi",
    "subject_en": "Psychology",
    "preferredLabel_nb": "Kognitiv dissonans",
    "preferredLabel_nn": "Kognitiv dissonans",
    "preferredLabel_en": "Cognitive dissonance",
    "alternativeLabel_nb": "Mental uoverensstemmelse",
    "alternativeLabel_nn": "Mental uovereinstemmelse",
    "alternativeLabel_en": "Mental inconsistency",
    "definition_nb": "Den mentale konflikten som oppstår når en persons overbevisninger eller antakelser blir motsagt av ny informasjon.",
    "definition_nn": "Den mentale konflikten som oppstår når ein person sine overtydingar eller føresetnader blir motsagt av ny informasjon.",
    "definition_en": "The mental conflict that occurs when a person's beliefs or assumptions are contradicted by new information.",
    "definition_lastUpdated": "2024-07-07"
  },
  {
    "id": "8",
    "subject_nb": "Økonomi",
    "subject_nn": "Økonomi",
    "subject_en": "Economics",
    "preferredLabel_nb": "Inflasjon",
    "preferredLabel_nn": "Inflasjon",
    "preferredLabel_en": "Inflation",
    "alternativeLabel_nb": "Prisstigning",
    "alternativeLabel_nn": "Prisstigning",
    "alternativeLabel_en": "Price increase",
    "definition_nb": "En generell økning i prisnivået i en økonomi over tid, som resulterer i en reduksjon av pengenes kjøpekraft.",
    "definition_nn": "Ein generell auke i prisnivået i ein økonomi over tid, som resulterer i ein reduksjon av pengane si kjøpekraft.",
    "definition_en": "A general increase in prices and fall in the purchasing value of money over time in an economy.",
    "definition_lastUpdated": "2024-07-08"
  },
  {
    "id": "9",
    "subject_nb": "Lingvistikk",
    "subject_nn": "Lingvistikk",
    "subject_en": "Linguistics",
    "preferredLabel_nb": "Fonem",
    "preferredLabel_nn": "Fonem",
    "preferredLabel_en": "Phoneme",
    "alternativeLabel_nb": "Språklyd",
    "alternativeLabel_nn": "Språklyd",
    "alternativeLabel_en": "Speech sound",
    "definition_nb": "Den minste lydenhet i et språk som kan skille mellom ordenes betydning.",
    "definition_nn": "Den minste lydeininga i eit språk som kan skilje mellom orda si tyding.",
    "definition_en": "The smallest unit of sound in a language that can distinguish between word meanings.",
    "definition_lastUpdated": "2024-07-09"
  },
  {
    "id": "10",
    "subject_nb": "Filosofi",
    "subject_nn": "Filosofi",
    "subject_en": "Philosophy",
    "preferredLabel_nb": "Epistemologi",
    "preferredLabel_nn": "Epistemologi",
    "preferredLabel_en": "Epistemology",
    "alternativeLabel_nb": "Erkjennelsesteori",
    "alternativeLabel_nn": "Erkjenningsteori",
    "alternativeLabel_en": "Theory of knowledge",
    "definition_nb": "Den grenen av filosofi som studerer kunnskapens natur, opprinnelse og grenser.",
    "definition_nn": "Den greina av filosofi som studerer kunnskapen sin natur, opphav og grenser.",
    "definition_en": "The branch of philosophy that studies the nature, origin, and limits of human knowledge.",
    "definition_lastUpdated": "2024-07-10"
  },
  {
    "id": "11",
    "subject_nb": "Sosiologi",
    "subject_nn": "Sosiologi",
    "subject_en": "Sociology",
    "preferredLabel_nb": "Sosialisering",
    "preferredLabel_nn": "Sosialisering",
    "preferredLabel_en": "Socialization",
    "alternativeLabel_nb": "Sosial læring",
    "alternativeLabel_nn": "Sosial læring",
    "alternativeLabel_en": "Social learning",
    "definition_nb": "Prosessen der individer lærer og internaliserer normer, verdier og atferdsmønstre i sitt samfunn.",
    "definition_nn": "Prosessen der individ lærer og internaliserer normer, verdiar og åtferdsmønster i samfunnet sitt.",
    "definition_en": "The process through which individuals learn and internalize the norms, values, and behaviors of their society.",
    "definition_lastUpdated": "2024-07-11"
  },
  {
    "id": "12",
    "subject_nb": "Astronomi",
    "subject_nn": "Astronomi",
    "subject_en": "Astronomy",
    "preferredLabel_nb": "Galakse",
    "preferredLabel_nn": "Galakse",
    "preferredLabel_en": "Galaxy",
    "alternativeLabel_nb": "Stjernesystem",
    "alternativeLabel_nn": "Stjernesystem",
    "alternativeLabel_en": "Star system",
    "definition_nb": "En massiv samling av stjerner, gass, støv og mørk materie som holdes sammen av tyngdekraften.",
    "definition_nn": "Ei massiv samling av stjerner, gass, støv og mørk materie som vert haldne saman av tyngdekrafta.",
    "definition_en": "A vast collection of stars, gas, dust, and dark matter held together by gravity.",
    "definition_lastUpdated": "2024-07-12"
  },
  {
    "id": "13",
    "subject_nb": "Medisin",
    "subject_nn": "Medisin",
    "subject_en": "Medicine",
    "preferredLabel_nb": "Homeostase",
    "preferredLabel_nn": "Homeostase",
    "preferredLabel_en": "Homeostasis",
    "alternativeLabel_nb": "Likevekt",
    "alternativeLabel_nn": "Likevekt",
    "alternativeLabel_en": "Equilibrium",
    "definition_nb": "Kroppens evne til å opprettholde et stabilt indre miljø til tross for endringer i det ytre miljøet.",
    "definition_nn": "Kroppen si evne til å oppretthalde eit stabilt indre miljø trass i endringar i det ytre miljøet.",
    "definition_en": "The body's ability to maintain a stable internal environment despite changes in the external environment.",
    "definition_lastUpdated": "2024-07-13"
  },
  {
    "id": "14",
    "subject_nb": "Kunsthistorie",
    "subject_nn": "Kunsthistorie",
    "subject_en": "Art History",
    "preferredLabel_nb": "Impresjonisme",
    "preferredLabel_nn": "Impresjonisme",
    "preferredLabel_en": "Impressionism",
    "alternativeLabel_nb": "Inntrykkskunst",
    "alternativeLabel_nn": "Inntrykkskunst",
    "alternativeLabel_en": "Impression art",
    "definition_nb": "En kunstbevegelse som oppsto på slutten av 1800-tallet, kjennetegnet ved å fange visuelle inntrykk av lys og bevegelse.",
    "definition_nn": "Ei kunstrørsle som oppstod på slutten av 1800-talet, kjenneteikna ved å fange visuelle inntrykk av lys og rørsle.",
    "definition_en": "An art movement that emerged in the late 19th century, characterized by capturing visual impressions of light and movement.",
    "definition_lastUpdated": "2024-07-14"
  },
  {
    "id": "15",
    "subject_nb": "Miljøvitenskap",
    "subject_nn": "Miljøvitskap",
    "subject_en": "Environmental Science",
    "preferredLabel_nb": "Bærekraft",
    "preferredLabel_nn": "Berekraft",
    "preferredLabel_en": "Sustainability",
    "alternativeLabel_nb": "Bærekraftig utvikling",
    "alternativeLabel_nn": "Berekraftig utvikling",
    "alternativeLabel_en": "Sustainable development",
    "definition_nb": "Prinsippet om å møte dagens behov uten å kompromittere fremtidige generasjoners evne til å møte sine egne behov.",
    "definition_nn": "Prinsippet om å møte dagens behov utan å kompromittere framtidige generasjonar si evne til å møte sine eigne behov.",
    "definition_en": "The principle of meeting present needs without compromising the ability of future generations to meet their own needs.",
    "definition_lastUpdated": "2024-07-15"
  }
]